baseurl      = "https://kaholaz.net"
title        = "Sebastian Bugge"
languageCode = "nb-NO"
theme        = "hello-friend-ng"
paginate     = 10

PygmentsCodeFences = true
PygmentsStyle = "monokai"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "problemløser, tenker, student"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  # enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "En liten blogg for personlige prosjekter og tanker."
  keywords = "homepage, blog"
  images = [""]

	[params.logo]
		logoText = "cd $HOME"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

defaultContentLanguage = "no"
defaultContentLanguageInSubdir = true

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "Om"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Innlegg"
    url        = "posts/"
